apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    capacity.cluster-autoscaler.kubernetes.io/labels: kubernetes.io/arch=amd64
    machine.openshift.io/GPU: "0"
    machine.openshift.io/memoryMb: "65536"
    machine.openshift.io/vCPU: "16"
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-l7p6s-jmcmt
  name: cluster-l7p6s-jmcmt-worker-us-east-2b-gpu
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-l7p6s-jmcmt
      machine.openshift.io/cluster-api-machineset: cluster-l7p6s-jmcmt-worker-us-east-2b-gpu
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-l7p6s-jmcmt
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: cluster-l7p6s-jmcmt-worker-us-east-2b-gpu
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          ami:
            id: ami-078e26f293629fe91
          apiVersion: machine.openshift.io/v1beta1
          blockDevices:
          - ebs:
              encrypted: true
              iops: 0
              kmsKey:
                arn: ""
              volumeSize: 100
              volumeType: gp2
          capacityReservationId: ""
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: cluster-l7p6s-jmcmt-worker-profile
          instanceType: g4dn.xlarge
          kind: AWSMachineProviderConfig
          metadata:
          metadataServiceOptions: {}
          placement:
            availabilityZone: us-east-2b
            region: us-east-2
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - cluster-l7p6s-jmcmt-node
          - filters:
            - name: tag:Name
              values:
              - cluster-l7p6s-jmcmt-lb
          subnet:
            filters:
            - name: tag:Name
              values:
              - cluster-l7p6s-jmcmt-subnet-private-us-east-2b
          tags:
          - name: kubernetes.io/cluster/cluster-l7p6s-jmcmt
            value: owned
          - name: Stack
            value: project ocp4-cluster-l7p6s
          - name: env_type
            value: ocp4-cluster
          - name: guid
            value: l7p6s
          - name: owner
            value: unknown
          - name: platform
            value: RHPDS
          - name: uuid
            value: 5bbd39ff-95f6-50f0-b2dd-054c8d78ba26
          userDataSecret:
            name: worker-user-data
