apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    capacity.cluster-autoscaler.kubernetes.io/labels: kubernetes.io/arch=amd64
    machine.openshift.io/GPU: "0"
    machine.openshift.io/memoryMb: "65536"
    machine.openshift.io/vCPU: "16"
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-v4kj7-s57hm
  name: cluster-v4kj7-s57hm-worker-us-east-2a-gpu
  namespace: openshift-machine-api
spec:
  replicas: {{.Values.GPU_REPLICAS}}
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-v4kj7-s57hm
      machine.openshift.io/cluster-api-machineset: cluster-v4kj7-s57hm-worker-us-east-2a-gpu
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-v4kj7-s57hm
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: cluster-v4kj7-s57hm-worker-us-east-2a-gpu
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          ami:
            id: ami-078e26f293629fe91
          apiVersion: machine.openshift.io/v1beta1
          blockDevices:
          - ebs:
              encrypted: true
              iops: 0
              kmsKey:
                arn: ""
              volumeSize: 100
              volumeType: gp2
          capacityReservationId: ""
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: cluster-v4kj7-s57hm-worker-profile
          instanceType: {{.Values.GPU_TYPE_AWS}}
          kind: AWSMachineProviderConfig
          metadata:
          metadataServiceOptions: {}
          placement:
            availabilityZone: us-east-2a
            region: us-east-2
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - cluster-v4kj7-s57hm-node
          - filters:
            - name: tag:Name
              values:
              - cluster-v4kj7-s57hm-lb
          subnet:
            filters:
            - name: tag:Name
              values:
              - cluster-v4kj7-s57hm-subnet-private-us-east-2a
          tags:
          - name: kubernetes.io/cluster/cluster-v4kj7-s57hm
            value: owned
          - name: Stack
            value: project ocp4-cluster-v4kj7
          - name: env_type
            value: ocp4-cluster
          - name: guid
            value: v4kj7
          - name: owner
            value: unknown
          - name: platform
            value: RHPDS
          - name: uuid
            value: 76686fe7-f2e6-5487-9077-d5243728b0d2
          userDataSecret:
            name: worker-user-data
